### ISSUE TITLE
Upgrade SDK to OpenAPI v2 #27

### ISSUE THREAD

**Issue by vincentdelitz** [corbado/corbado-go#30]
# Background
Due to the upgrade to OpenAPI v2, we need to adapt our Go Backend SDK as well. We will cut down on the services to only three:
- sessions
- users
- identifiers

This implies some more changes as well (see below).

# TODO
- [x] Implement the three new services / cut the SDKs down to these three (see above).
- [x] Extend config with Frontend API URL and Backend API URL
- [x] Create example as basis for integration guide
- [x] Change the Corbado Backend API to "https://backendapi.cloud.corbado.io"
- [x] Update the respective README accordingly
- [ ] Please check the code examples (if applicable) and see if we need to update things there as well:
   - [ ] Wizard (https://app.corbado.com/`<project-ID>`/project-setup/golang)
